use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct AdmissionV2 {
    pub record_id: String,
    pub schema_version: u32,
    pub admitted_at: String,
    pub description: String,
    #[serde(default)]
    pub changes: Vec<Change>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(tag = "kind", rename_all = "kebab-case")]
pub enum Change {
    TheoreticalModel {
        model_id: String,
        name: String,
        description: String,
    },
    TheoreticalModelAssessment {
        assessment_id: String,
        model_id: String,
        revision: u32,
        event_kind: String,
        occurred_at: String,
        epistemic_status: String,
        rationale: String,
        scope: String,
    },
    Material {
        material_id: String,
        name: String,
        description: String,
    },
    MaterialAssessment {
        assessment_id: String,
        material_id: String,
        revision: u32,
        event_kind: String,
        occurred_at: String,
        material_classification: String,
        epistemic_status: String,
        rationale: String,
        scope: String,
    },
    PhysicalMechanism {
        mechanism_id: String,
        name: String,
        description: String,
    },
    MechanismAssessment {
        assessment_id: String,
        mechanism_id: String,
        revision: u32,
        event_kind: String,
        occurred_at: String,
        epistemic_status: String,
        rationale: String,
        scope: String,
    },
    Interface {
        interface_id: String,
        name: String,
        observation_kind: String,
        units: String,
        description: String,
    },
    InterfaceAssessment {
        assessment_id: String,
        interface_id: String,
        revision: u32,
        event_kind: String,
        occurred_at: String,
        epistemic_status: String,
        rationale: String,
        scope: String,
    },
    ProcessPort {
        port_id: String,
        name: String,
        port_type: String,
        model_id: String,
        material_id: String,
        mechanism_id: String,
        interface_id: String,
        description: String,
    },
    TypedMorphism {
        morphism_id: String,
        name: String,
        model_id: String,
        material_id: String,
        mechanism_id: String,
        interface_id: String,
        source_port_id: String,
        target_port_id: String,
        morphism_type: String,
        description: String,
    },
    MorphismAssessment {
        assessment_id: String,
        morphism_id: String,
        revision: u32,
        event_kind: String,
        occurred_at: String,
        validation_status: String,
        rationale: String,
        scope: String,
    },
    MorphismPath {
        path_id: String,
        name: String,
        model_id: String,
        material_id: String,
        mechanism_id: String,
        interface_id: String,
        source_port_id: String,
        target_port_id: String,
        description: String,
        steps: Vec<String>,
    },
    SiegeCell {
        cell_id: String,
        name: String,
        model_id: String,
        material_id: String,
        mechanism_id: String,
        interface_id: String,
    },
    SiegeCellMorphism {
        cell_id: String,
        morphism_id: String,
        relationship: String,
    },
    SiegeCellPath {
        cell_id: String,
        path_id: String,
        relationship: String,
    },
    SiegeCellAssessment {
        assessment_id: String,
        cell_id: String,
        revision: u32,
        event_kind: String,
        occurred_at: String,
        epistemic_status: String,
        rationale: String,
        scope: String,
    },
    SiegeCellDecision {
        decision_id: String,
        cell_id: String,
        revision: u32,
        event_kind: String,
        occurred_at: String,
        status: String,
        rationale: String,
        scope: String,
    },
    ParameterDefinition {
        parameter_id: String,
        name: String,
        symbol: String,
        units: String,
        description: String,
    },
    ParameterRegion {
        region_id: String,
        cell_id: String,
        name: String,
    },
    ParameterRegionVersion {
        region_version_id: String,
        region_id: String,
        revision: u32,
        event_kind: String,
        occurred_at: String,
        region_kind: String,
        predeclared: bool,
        rationale: String,
        scope: String,
    },
    ParameterRegionValue {
        region_version_id: String,
        parameter_id: String,
        lower_value: Option<f64>,
        upper_value: Option<f64>,
        exact_text: Option<String>,
        units: String,
    },
    Problem {
        problem_id: String,
        label: String,
    },
    ProblemVersion {
        problem_version_id: String,
        problem_id: String,
        revision: u32,
        event_kind: String,
        occurred_at: String,
        problem_statement: String,
        rationale: String,
        scope: String,
    },
    Conjecture {
        conjecture_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        problem_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        cell_id: Option<String>,
        label: String,
    },
    ConjectureVersion {
        conjecture_version_id: String,
        conjecture_id: String,
        revision: u32,
        event_kind: String,
        occurred_at: String,
        statement: String,
        rationale: String,
        scope: String,
    },
    ConjectureFraming {
        framing_id: String,
        conjecture_version_id: String,
        framing_order: u32,
        coordinate_key_version: String,
        coordinate_key: String,
        validation_generation: String,
        model_id: String,
        material_id: String,
        mechanism_id: String,
        interface_id: String,
        coordinate_classification: String,
        cell_id: Option<String>,
        framing_rationale: String,
    },
    ConjectureDisposition {
        disposition_id: String,
        conjecture_id: String,
        conjecture_version_id: String,
        revision: u32,
        event_kind: String,
        occurred_at: String,
        status: String,
        rationale: String,
        scope: String,
    },
    ResearchTopic {
        topic_id: String,
        label: String,
    },
    ResearchTopicVersion {
        topic_version_id: String,
        topic_id: String,
        revision: u32,
        event_kind: String,
        occurred_at: String,
        title: String,
        open_problem: String,
        why_open: String,
        scope: String,
        next_discriminating_criticism_or_test: String,
        non_claims: String,
    },
    ResearchTopicLocus {
        locus_id: String,
        topic_version_id: String,
        locus_order: u32,
        locus_kind: String,
    },
    ResearchTopicOrigin {
        origin_id: String,
        topic_version_id: String,
        origin_order: u32,
        origin_kind: String,
        problem_version_id: Option<String>,
        conjecture_version_id: Option<String>,
        relationship: String,
        rationale: String,
    },
    ResearchTopicFramingLink {
        framing_link_id: String,
        topic_version_id: String,
        conjecture_framing_id: String,
        relationship: String,
        rationale: String,
    },
    ResearchTopicEvidenceLink {
        evidence_link_id: String,
        topic_version_id: String,
        artifact_id: String,
        relationship: String,
        rationale: String,
    },
    ResearchTopicTestLink {
        test_link_id: String,
        topic_version_id: String,
        criterion_id: String,
        relationship: String,
        rationale: String,
    },
    ResearchTopicPublicLink {
        public_link_id: String,
        topic_version_id: String,
        link_order: u32,
        link_kind: String,
        public_record_id: String,
        target_proposal_id: String,
        target_revision: u32,
        content_sha256: String,
        relationship: String,
        rationale: String,
    },
    ResearchTopicRelation {
        relation_id: String,
        source_topic_version_id: String,
        target_topic_version_id: String,
        relation_kind: String,
        relation_claim: String,
        relation_scope: String,
    },
    ResearchTopicWorkflowEvent {
        workflow_event_id: String,
        topic_id: String,
        revision: u32,
        event_kind: String,
        occurred_at: String,
        status: String,
        rationale: String,
        scope: String,
    },
    FalsificationCriterion {
        criterion_id: String,
        conjecture_version_id: String,
        description: String,
        metric: String,
        comparator: String,
        threshold_value: Option<f64>,
        threshold_text: Option<String>,
        units: String,
        predeclared: bool,
    },
    Protocol {
        protocol_id: String,
        name: String,
    },
    ProtocolVersion {
        protocol_version_id: String,
        protocol_id: String,
        revision: u32,
        event_kind: String,
        occurred_at: String,
        predeclared: bool,
        seed_count: u32,
        null_trials: Option<u32>,
        null_quantile: Option<f64>,
        rationale: String,
        scope: String,
    },
    ProtocolProvenanceAssessment {
        assessment_id: String,
        protocol_version_id: String,
        revision: u32,
        event_kind: String,
        occurred_at: String,
        config_uri: Option<String>,
        config_sha256: Option<String>,
        completeness_status: String,
        rationale: String,
        scope: String,
    },
    Run {
        run_id: String,
        protocol_version_id: String,
        cell_id: String,
        code_commit: String,
        summary: String,
    },
    RunAssessment {
        assessment_id: String,
        run_id: String,
        revision: u32,
        event_kind: String,
        occurred_at: String,
        operational_status: String,
        epistemic_status: String,
        rationale: String,
        scope: String,
    },
    EvidenceArtifact {
        artifact_id: String,
        run_id: String,
        artifact_kind: String,
        artifact_uri: String,
        expected_sha256: String,
        canonical_detail: bool,
        detail_row_count: Option<u64>,
        description: String,
    },
    GateResult {
        gate_result_id: String,
        run_id: String,
        criterion_id: Option<String>,
        gate_name: String,
        evidence_polarity: String,
        passed: bool,
        metric_value: Option<f64>,
        metric_text: Option<String>,
        units: String,
        seed_pass_count: Option<u32>,
        seed_required_count: Option<u32>,
        decision_scope: String,
        limitation: String,
    },
    GateResultSupersession {
        supersession_id: String,
        prior_gate_result_id: String,
        replacement_gate_result_id: String,
        occurred_at: String,
        reason: String,
    },
    Comparison {
        comparison_id: String,
        run_id: String,
        baseline_run_id: Option<String>,
        control_relationship: String,
        metric: String,
        evidence_polarity: String,
        minimum_delta: Option<f64>,
        maximum_delta: Option<f64>,
        mean_delta: Option<f64>,
        units: String,
        decision_scope: String,
    },
    ComparisonSupersession {
        supersession_id: String,
        prior_comparison_id: String,
        replacement_comparison_id: String,
        occurred_at: String,
        reason: String,
    },
    LedgerLink {
        ledger_link_id: String,
        ledger_number: u32,
        ledger_title: String,
        ledger_path: String,
        ledger_sha256: String,
        relation: String,
        admitted_claim: String,
    },
    ProvenanceClaim {
        provenance_id: String,
        provenance_kind: String,
        ledger_link_id: Option<String>,
        claim_text: String,
        target: ProvenanceTarget,
    },
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(tag = "target_kind", content = "target_id", rename_all = "kebab-case")]
pub enum ProvenanceTarget {
    TheoreticalModel(String),
    TheoreticalModelAssessment(String),
    Material(String),
    MaterialAssessment(String),
    Mechanism(String),
    MechanismAssessment(String),
    Interface(String),
    InterfaceAssessment(String),
    ProcessPort(String),
    Morphism(String),
    MorphismAssessment(String),
    Path(String),
    Cell(String),
    CellAssessment(String),
    CellDecision(String),
    Parameter(String),
    Region(String),
    RegionVersion(String),
    Problem(String),
    ProblemVersion(String),
    Conjecture(String),
    ConjectureVersion(String),
    ConjectureFraming(String),
    ConjectureDisposition(String),
    ResearchTopic(String),
    ResearchTopicVersion(String),
    ResearchTopicWorkflowEvent(String),
    ResearchTopicRelation(String),
    Criterion(String),
    Protocol(String),
    ProtocolVersion(String),
    ProtocolAssessment(String),
    Run(String),
    RunAssessment(String),
    Artifact(String),
    GateResult(String),
    GateSupersession(String),
    Comparison(String),
    ComparisonSupersession(String),
}
