-- Public scientific and governance history is append-only. Operational OAuth/session/idempotency
-- rows and proposal cache columns are the deliberately narrow mutable exception.
CREATE TRIGGER proposal_revisions_no_update BEFORE UPDATE ON proposal_revisions BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER proposal_revisions_no_delete BEFORE DELETE ON proposal_revisions BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER theoretical_model_details_no_update BEFORE UPDATE ON theoretical_model_details BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER theoretical_model_details_no_delete BEFORE DELETE ON theoretical_model_details BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER physical_material_details_no_update BEFORE UPDATE ON physical_material_details BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER physical_material_details_no_delete BEFORE DELETE ON physical_material_details BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER physical_mechanism_details_no_update BEFORE UPDATE ON physical_mechanism_details BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER physical_mechanism_details_no_delete BEFORE DELETE ON physical_mechanism_details BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER observation_interface_details_no_update BEFORE UPDATE ON observation_interface_details BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER observation_interface_details_no_delete BEFORE DELETE ON observation_interface_details BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER existing_member_assessment_details_no_update BEFORE UPDATE ON existing_member_assessment_details BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER existing_member_assessment_details_no_delete BEFORE DELETE ON existing_member_assessment_details BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER existing_member_correction_details_no_update BEFORE UPDATE ON existing_member_correction_details BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER existing_member_correction_details_no_delete BEFORE DELETE ON existing_member_correction_details BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER ontology_change_details_no_update BEFORE UPDATE ON ontology_change_details BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER ontology_change_details_no_delete BEFORE DELETE ON ontology_change_details BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER proposal_state_events_no_update BEFORE UPDATE ON proposal_state_events BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER proposal_state_events_no_delete BEFORE DELETE ON proposal_state_events BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER proposal_evidence_no_update BEFORE UPDATE ON proposal_evidence BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER proposal_evidence_no_delete BEFORE DELETE ON proposal_evidence BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER proposal_references_no_update BEFORE UPDATE ON proposal_references BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER proposal_references_no_delete BEFORE DELETE ON proposal_references BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER criticisms_no_update BEFORE UPDATE ON criticisms BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER criticisms_no_delete BEFORE DELETE ON criticisms BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER criticism_replies_no_update BEFORE UPDATE ON criticism_replies BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER criticism_replies_no_delete BEFORE DELETE ON criticism_replies BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER criticism_references_no_update BEFORE UPDATE ON criticism_references BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER criticism_references_no_delete BEFORE DELETE ON criticism_references BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER scoped_test_reports_no_update BEFORE UPDATE ON scoped_test_reports BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER scoped_test_reports_no_delete BEFORE DELETE ON scoped_test_reports BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER test_report_references_no_update BEFORE UPDATE ON test_report_references BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER test_report_references_no_delete BEFORE DELETE ON test_report_references BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER competing_interpretations_no_update BEFORE UPDATE ON competing_interpretations BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER competing_interpretations_no_delete BEFORE DELETE ON competing_interpretations BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER moderation_actions_no_update BEFORE UPDATE ON moderation_actions BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER moderation_actions_no_delete BEFORE DELETE ON moderation_actions BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER appeals_no_update BEFORE UPDATE ON appeals BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER appeals_no_delete BEFORE DELETE ON appeals BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER appeal_state_events_no_update BEFORE UPDATE ON appeal_state_events BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER appeal_state_events_no_delete BEFORE DELETE ON appeal_state_events BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER maintainer_exports_no_update BEFORE UPDATE ON maintainer_exports BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER maintainer_exports_no_delete BEFORE DELETE ON maintainer_exports BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER admission_links_no_update BEFORE UPDATE ON admission_links BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER admission_links_no_delete BEFORE DELETE ON admission_links BEGIN SELECT RAISE(ABORT, 'immutable public record'); END;
CREATE TRIGGER allowed_proposal_transitions_no_update BEFORE UPDATE ON allowed_proposal_state_transitions BEGIN SELECT RAISE(ABORT, 'governance vocabulary is immutable in schema v1'); END;
CREATE TRIGGER allowed_proposal_transitions_no_delete BEFORE DELETE ON allowed_proposal_state_transitions BEGIN SELECT RAISE(ABORT, 'governance vocabulary is immutable in schema v1'); END;
CREATE TRIGGER allowed_appeal_transitions_no_update BEFORE UPDATE ON allowed_appeal_state_transitions BEGIN SELECT RAISE(ABORT, 'governance vocabulary is immutable in schema v1'); END;
CREATE TRIGGER allowed_appeal_transitions_no_delete BEFORE DELETE ON allowed_appeal_state_transitions BEGIN SELECT RAISE(ABORT, 'governance vocabulary is immutable in schema v1'); END;
